language: swift  #1
osx_image: xcode9.3 #2
xcode_project: CIProject.xcodeproj #3
xcode_scheme: CIProject #4
#xcode_sdk: iphonesimulator11.3 #5
xcodebuild test -workspace $XCWORKSPACE -scheme $XCSCHEME  -destination 'platform=iOS Simulator,name=iPhone 6 Plus' | xcpretty -c && exit ${PIPESTATUS[0]}
