language: swift  #1
osx_image: xcode9.3 #2

script:
    - xcodebuild clean build -sdk iphonesimulator -project ./CIProject/CIProject.xcodeproj -scheme ./CIProject/CIProjectTests CODE_SIGNING_REQUIRED=NO
