language: swift  #1
osx_image: xcode9.3 #2
xcode_project: CIProject.xcodeproj #3
#xcode_scheme: CIProject #4

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace CIProject.xcworkspace -scheme ProjectTests CODE_SIGNING_REQUIRED=NO
