language: swift  #1
osx_image: xcode9.3 #2

notification:
  email:
    - deepak.kumar@sourcefuse.com

script:
    - xcodebuild clean build -sdk iphonesimulator -project ./CIProject/CIProject.xcodeproj -scheme CIProject CODE_SIGNING_REQUIRED=NO
