language: swift  #1
osx_image: xcode9.3 #2

#before_install:
#- sudo gem install fastlane

notifications:
  email:
    recipients:
      - deepak.kumar@sourcefuse.com
    on_success: always # default: change
    on_failure: always # default: always
addons:
  sonarcloud:
    organization: "deepakkr25-github" # the key of the org you chose at step #3
    token:
      secure: 7cc9f4ec2d70c33809e51262d70c524175a41692 # encrypted value of your token
script:
    #- xcodebuild clean build -sdk iphonesimulator -project ./CIProject/CIProject.xcodeproj -scheme CIProject CODE_SIGNING_REQUIRED=NO
    - sonar-scanner -X
    - fastlane test
    #fastlane scan --project CIProject.xcodeproj --scheme CIProject --device iPhone 6 --clean
