language: swift  #1
osx_image: xcode9.3 #2

notifications:
  email:
    recipients:
      - deepak.kumar@sourcefuse.com
    on_success: always # default: change
    on_failure: always # default: always

install:
  - bundle install

script:
    #- xcodebuild clean build -sdk iphonesimulator -project ./CIProject/CIProject.xcodeproj -scheme CIProject CODE_SIGNING_REQUIRED=NO
    - fastlane test
    #fastlane scan --project CIProject.xcodeproj --scheme CIProject --device iPhone 6 --clean
